### ISSUE TITLE
Не совсем понимаю этот момент :)

### ISSUE THREAD

**Issue by AnyaZayceva** [NikitaShtytko/InstagramProject#6]
https://github.com/NikitaShtytko/InstagramProject/blob/17e078056d75318a0e18bb390e23b3b3fe8cef82/backend/src/main/java/com/netcracker/edu/backend/entity/Ban.java#L19

    @Column(name = "user_id")
    private Long userId;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    private User user;

**Comment by NikitaShtytko** [comment]
почему user_id?

**Comment by AnyaZayceva** [comment]
Почему дублируем
